# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [6]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [10]:
A = np.arange(1, 16).reshape(3,5)

In [13]:
A.shape

(3, 5)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [30]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [33]:
print(B-C)
print()
print(B*C)
print()
print(B@C)



[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [70]:
B = np.arange(1, 10).reshape(3, 3)

print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [122]:
print(np.exp(B),"Exponentiate each number \n")
print(np.min(B),"Minimum value in the whole matrix\n")
print(np.min(B, axis=1),"Minimum value in each row\n")
print(np.min(B, axis=0),"Minimum value in each column\n")
print(np.argmin(B),"Index value for the minimum value in the whole matrix\n")
print(np.argmin(B,axis=1),"Index for the minimum value in each row\n")
print(np.sum(B),'The sum of all elements')
print(np.mean(B,axis=0), 'The mean of each column')
print(np.median(B,axis=0), 'The median of each column')



[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] Exponentiate each number 

1 Minimum value in the whole matrix

[1 4 7] Minimum value in each row

[1 2 3] Minimum value in each column

0 Index value for the minimum value in the whole matrix

[0 0 0] Index for the minimum value in each row

45 The sum of all elements
[4. 5. 6.] The mean of each column
[4. 5. 6.] The median of each column


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [124]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [134]:
A[1]


array([ 6,  7,  8,  9, 10])

**Answer:**

In [133]:
# It means that you include all the elements in the chosen axes. If you print out A[1,1] you will get the second row and the second column, 7. If you leave out 1 and write A[1] you will get the entire row. it's like writing A[1,:]. It works with multi dimensions as well. 


array([ 6,  7,  8,  9, 10])

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [135]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [136]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [142]:
for i in A:
    for y in i:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [155]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# The code converts a series of numbers in a row (one dimension) to a tree dimensional structure. Now you can navigate trough the data in a more structural way. 
 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [156]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [157]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [158]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [221]:
import numpy as np

def add_mult_matrices(matrix_1, matrix_2, action):
    if isinstance(matrix_1,np.ndarray) == True and isinstance(matrix_2,np.ndarray) == True:
        if action == "add":
            
            if matrix_1.shape == matrix_2.shape:
                return matrix_1 + matrix_2
            
            else:
                print("The matrixes have different dimensions.")
                
        elif action == "multiply":
            if matrix_1.shape[1] == matrix_2.shape[0]:
                return matrix_1 @ matrix_2
            
            else:
                print("The number of columns in the first matrix is not equal to the number of rows in the second matrix.")
        
    else:
        print("At least one of the matrixes are not of the right type.")
            
        pass
        
    

M_1 = np.arange(1, 11).reshape(5, 2)
M_2 = np.arange(1, 11).reshape(2, 5)
M_3 = 5
A_1 = 'add'
A_2 = 'multiply'

print(add_mult_matrices(M_1, M_2, A_2))



[[ 13  16  19  22  25]
 [ 27  34  41  48  55]
 [ 41  52  63  74  85]
 [ 55  70  85 100 115]
 [ 69  88 107 126 145]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [97]:
# 10.1.1
import numpy as np
import numpy.linalg as norm
list_2 = [4,3]
tio_var = np.array(list_2).reshape(1,2)
# 10.1.1 a)
print("Vektorn har dimensionen", tio_var.shape,"\n")
# 10.1.1 b)
print(tio_var * 5,"\n")
# 10.1.1 c)
print(tio_var * 3,"\n")
# 10.1.1 d)
print(tio_var * 3 + tio_var * 5,"\n")
# 10.1.1 e)
print(tio_var * 8,"\n")

Vektorn har dimensionen (1, 2) 

[[20 15]] 

[[12  9]] 

[[32 24]] 

[[32 24]] 



In [105]:

# 10.1.1 f)
print(tio_var*4-tio_var,"\n")
# 10.1.1 g)
print(tio_var.transpose(), "\n Transponerad blir vektorn", tio_var.transpose().shape,"\n")
# 10.1.1 h)
print("Nej det är inte definierat eftersom de inte har samma dimension","\n")
# 10.1.1 i)
print(tio_var, "\n", np.linalg.norm(tio_var),"\n")


[[12  9]] 

[[4]
 [3]] 
 Transponerad blir vektorn (2, 1) 

Nej det är inte definierat eftersom de inte har samma dimension 

[[4 3]] 
 5.0 



In [150]:
list_1 = [3, 7, 0, 11]
tio_var2 = np.array(list_1).reshape(4,1)

# 10.1.2 a)
print("Vektorn har dimensionen", tio_var2.shape, "\n")
# 10.1.2 b)
print(tio_var2 * 2, "\n")
# 10.1.2 c)
print(tio_var2 * 5 + tio_var2 * 2, "\n")
# 10.1.2 d)
print(tio_var2 * 4 - tio_var2 * 2, "\n")
# 10.1.2 e)
print("Transponerad blir vektorn ",np.transpose(tio_var2), " och vektorn får dimensionen", np.transpose(tio_var2).shape, "\n")
# 10.1.2 f)
print("||V|| blir ", np.linalg.norm(tio_var2),"\n")
# 10.1.3 a)
list_3 = [4,3,1,5]
list_4 = [2,3,1,1]
tio_var3 = np.array(list_3)
tio_var4 = np.array(list_4)
print("||V1|| blir ", np.linalg.norm(tio_var3),"\n")
print("||V1|| - ||V2|| blir", np.linalg.norm(tio_var3 - tio_var4))

Vektorn har dimensionen (4, 1) 

[[ 6]
 [14]
 [ 0]
 [22]] 

[[21]
 [49]
 [ 0]
 [77]] 

[[ 6]
 [14]
 [ 0]
 [22]] 

Transponerad blir vektorn  [[ 3  7  0 11]]  och vektorn får dimensionen (1, 4) 

||V|| blir  13.379088160259652 

||V1|| blir  7.14142842854285 

||V1|| - ||V2|| blir 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [161]:
list_a = [2,1,-1,1,-1,1]
list_b = [4,-2,1,2,-4,-2]
list_c = [1,2,2,1]
list_d = [3,4,4,3]
list_e = [1,2]
list_i = [1,0,0,1]
ten_two_a = np.array(list_a).reshape(2,3)
ten_two_b = np.array(list_b).reshape(2,3)
ten_two_c = np.array(list_c).reshape(2,2)
ten_two_d = np.array(list_d).reshape(2,2)
ten_two_e = np.array(list_e).reshape(2,1)
ten_two_i = np.array(list_i).reshape(2,2)

# 10.2.1 a)
print("10.2.1 a) \n", 2 * ten_two_a, "\n")
# 10.2.1 b)
print("10.2.1 b) \n", ten_two_b-ten_two_a * 2, "\n")
# 10.2.1 c)
print(f"10.2.1 c)\n Är ej definierat eftersom C är {ten_two_c.shape} och E är {ten_two_e.shape}. Men Python kommer fram till följande ändå: \n", 3 * ten_two_c - 2 * ten_two_e,"\n")
# 10.2.1 d)
print("10.2.1 d)\n", 2 * ten_two_d - 3 * ten_two_c, "\n")
# 10.2.1 e)
print("10.2.1 e)\n", ten_two_d.transpose() + 2 * ten_two_d)



10.2.1 a) 
 [[ 4  2 -2]
 [ 2 -2  2]] 

10.2.1 b) 
 [[ 0 -4  3]
 [ 0 -2 -4]] 

10.2.1 c)
 Är ej definierat eftersom C är (2, 2) och E är (2, 1). Men Python kommer fram till följande ändå: 
 [[ 1  4]
 [ 2 -1]] 

10.2.1 d)
 [[3 2]
 [2 3]] 

10.2.1 e)
 [[ 9 12]
 [12  9]]


In [190]:
# 10.2.1 f)
print("10.2.1 f)\n", ten_two_c.transpose() * 2 - ten_two_d.transpose() * 2,"\n")

# 10.2.1 g)
print("10.2.1 g)\n", "Ej definierad. Ej samma dinension. Testade koden ten_two_a.transpose() - ten_two_b och denna gång hanterade inte Python det heller.\n")

# 10.2.1 h)
print("10.2.1 h)", "Ej definierat, ej samma antal kolumner i A som rader i C\n")

# 10.2.1 i)
print("10.2.1 i)\n", ten_two_c @ ten_two_d,"\n")

# 10.2.1 j)
print("10.2.1 j)\n", ten_two_c @ ten_two_b,"\n")

# 10.2.1 k)
print("10.2.1 k)\n", ten_two_c @ ten_two_i,"\n")

# 10.2.1 l)
print("10.2.1 l)\n", ten_two_a @ ten_two_b.transpose(),"\n")

# 10.2.2
list_2_2 = [2, 3, 4, 5, 4, 1]
ten_two_two = np.array(list_2_2).reshape(2,3)
print("10.2.2\n", ten_two_two @ ten_two_two.transpose(),"\n")




10.2.1 f)
 [[-4 -4]
 [-4 -4]] 

10.2.1 g)
 Ej definierad. Ej samma dinension. Testade koden ten_two_a.transpose() - ten_two_b och denna gång hanterade inte Python det heller.

10.2.1 h) Ej definierat, ej samma antal kolumner i A som rader i C

10.2.1 i)
 [[11 10]
 [10 11]] 

10.2.1 j)
 [[  8 -10  -3]
 [ 10  -8   0]] 

10.2.1 k)
 [[1 2]
 [2 1]] 

10.2.1 l)
 [[5 2]
 [7 4]] 

10.2.2
 [[29 26]
 [26 42]] 



In [226]:
# 10.2.3
list_2_3_a = [1, 2, 2, 4]
list_2_3_b = [2, 1, 1, 3]
list_2_3_c = [4, 3, 0, 2]

ten_two_three_a = np.array(list_2_3_a).reshape(2,2)
ten_two_three_b = np.array(list_2_3_b).reshape(2,2)
ten_two_three_c = np.array(list_2_3_c).reshape(2,2)

print("Hypotesen att AB är lika med AC,", ten_two_three_a @ ten_two_three_b == ten_two_three_a @ ten_two_three_c, "\n AB = \n", ten_two_three_a @ ten_two_three_b, "\n AC = \n", ten_two_three_a @ ten_two_three_c,"\n vilket är lika\n")
print("Hypotesen att B INTE är lika med C: ", ten_two_three_b != ten_two_three_c, "\n B = \n", ten_two_three_b, "\n C= \n", ten_two_three_c)






Hypotesen att AB är lika med AC, [[ True  True]
 [ True  True]] 
 AB = 
 [[ 4  7]
 [ 8 14]] 
 AC = 
 [[ 4  7]
 [ 8 14]] 
 vilket är lika

Hypotesen att B INTE är lika med C:  [[ True  True]
 [ True  True]] 
 B = 
 [[2 1]
 [1 3]] 
 C= 
 [[4 3]
 [0 2]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [232]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [233]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [234]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123

print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [235]:
# When you check the base value you will get the value None for a Copy and the array content if it is a View. 
# A View is pointing towards another array and if you change the original array you will also change the view array and vice versa. 
# If you create a Copy of another array you will however not change the copy if the original is changed and the original will not change if you change the copy.